gestaoProjetos/urls.py
from django.conf.urls import url
from gestaoProjetos import views

app_name = 'gestaoProjetos'
urlpatterns = [
    url(r'^$', views.showcase, name='index'),
    url(r'^showcase$', views.showcase, name='showcase'),
    url(r'^projetos/(?P<projeto_id>\d+)/$', views.detalhes_projeto, name='detalhes_projeto'),
]

sigma/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gestaoProjetos.urls')),
]

gestaoProjetos/models.py
from django.db import models
from .DAOs.ProjetoDAO import ProjetoDAO

class Projeto(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(blank=True)
    inicio  = models.DateTimeField(auto_now_add=False)
    fim = models.DateTimeField(auto_now_add=False)
    progresso = models.FloatField()
    linkGithub = models.URLField(blank=True)
    linkGoogleDrive = models.URLField(blank=True)
    linkSlack = models.URLField(blank=True)
    linkTaiga = models.URLField(blank=True)

    # Enums
    SITUACAO_CHOICES = [('P', 'Pendente'), ('E', 'Em andamento'), ('F', 'Finalizado')]
    FASE_CHOICES = [('I', 'Inception'), ('C', 'Concepção'), ('D', 'Desenvolvimento'), ('M', 'Implantação'), ('T', 'TLE')]
    PRIORIDADE_CHOICES = [('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')]
    METODOLOGIA_CHOICES = [('C', 'Cascata'), ('I', 'Iterativo'), ('A', 'Agil'), ('E', 'Evolutivo')]
    situacao = models.CharField(max_length=1, choices=SITUACAO_CHOICES, default='P')
    fase = models.CharField(max_length=1, choices=FASE_CHOICES, default='I')
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, default='B')
    metodologia = models.CharField(max_length=1, choices=METODOLOGIA_CHOICES, default='C')

    # Relacionamentos
    # cliente = models.ForeignKey('gestaoProjetos.EntidadeExterna', models.CASCADE)

    objects = ProjetoDAO()

    def progresso_porcentagem(self):
        return int(self.progresso * 100)

    def __str__(self):
      return self.nome

class EntidadeExterna(models.Model):
    nome = models.CharField(max_length=50)
    pessoaContato = models.CharField(max_length=80)
    telefone = models.CharField(max_length=11)
    endereco = models.CharField(max_length=100)

    def __str__(self):
      return self.nome

gestaoProjetos/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, get_list_or_404, render
from gestaoProjetos.models import Projeto

def showcase(request):
    projetos = Projeto.objects.all()
    context = {'projetos': projetos}
    return render(request, 'showcase.html', context=context)

def detalhes_projeto(request, projeto_id):
    print(type(projeto_id))
    projeto = Projeto.objects.get(id=int(projeto_id))
    context = {'projeto': projeto}
    return render(request, 'detalhes_projeto.html', context=context)

templates/base.html
<!DOCTYPE html>
<head>
  <title>
    {% block title %} Sigma {% endblock %}
  </title>

  <!-- Boostrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Jquery -->
  <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>

  <!-- Boostrap JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- Custom CSS -->
  <style>
    /* Leave some empty around the body. */
    body {
      padding-top: 80px;
      padding-left: 40px;
      padding-right: 40px;
      padding-bottom: 40px;
    }
  </style>

</head>
<body>
  {% include 'navbar.html' %}
  {% block body %}{% endblock %}
</body>

templates/detalhes_projeto.html
{% extends "base.html" %}

{% block title %} {{ projeto.nome }} - Sigma {% endblock %}

{% block body %}

<h1> {{ projeto.nome | upper }} </h1>
<br>

<div class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.nome}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Descrição</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.descricao}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Inicio</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.inicio}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Fim</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.fim}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Progresso</label>
    <div class="col-sm-10">
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: {{projeto.progresso_porcentagem}}%;">
          {{projeto.progresso_porcentagem}}%
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Github</label>
    <div class="col-sm-10">
      <a class="form-control-static">{{projeto.linkGithub}}</a>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Google Drive</label>
    <div class="col-sm-10">
      <a class="form-control-static">{{projeto.linkGoogleDrive}}</a>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Slack</label>
    <div class="col-sm-10">
      <a class="form-control-static">{{projeto.linkSlack}}</a>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Taiga</label>
    <div class="col-sm-10">
      <a class="form-control-static">{{projeto.linkTaiga}}</a>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Situacao</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.get_situacao_display}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Fase</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.get_fase_display}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Prioridade</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.get_prioridade_display}}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Metodologia</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{projeto.get_metodologia_display}}</p>
    </div>
  </div>
</div>

<h2>Participantes</h2>
<br>
<h2>Patrocinadores</h2>
<br>
<h2>Tecnologias Usadas</h2>
<br>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %} Index - Sigma {% endblock %}

{% block body %}
<h1>My page title</h1>

<button type="button" class="btn btn-default btn-sm">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Star
</button>

<p>Lorem ipsum dolor sit amet, cum autem exerci te. Appareat legendos assentior ea nec. Et autem error eam. Detraxit posidonium voluptatibus ex sed, insolens instructior eu vel, per ex docendi perfecto. Utroque persecuti an est.</p>

<div class="well">
  <p>Ut est accumsan consequuntur, nec idque probatus postulant eu. Erant mollis complectitur ei eos, dicunt maluisset at sed, ut eum partem nonumes adipiscing. Ea debet ridens duo. Sit an errem essent, id alia viderer periculis vel. Vim sonet vocent intellegebat ne. Soluta commodo cu vel, case torquatos sed no. Ullum vocent interpretaris pro in, qui te clita accusam mentitum.</p>
</div>

<p>Vel no soleat rationibus. Ut stet euripidis vel, vidit nonumes gloriatur in vim. Quot labore eligendi ei his. Vel ne eleifend recteque omittantur. Et accusamus assentior mediocritatem sit, odio elaboraret dissentiunt ut pri. Duo semper doctus te, ne possit disputando cum.</p>

<p>Ad lorem putant vivendum sed, laudem verear no mel. Quaeque constituam interpretaris ea vix, munere argumentum per ea, et odio everti iriure pri. Eam ea vidisse omnesque tractatos. Iusto temporibus quo in, has id detracto consequat. At est intellegat necessitatibus.</p>

<p>Justo epicuri delicata an has, an nec augue labore comprehensam, an sit alii hendrerit. Purto brute voluptua vis ut. Pri erat labore at, admodum incorrupte quo et, ne dolorum admodum mei. Eu est viris assentior forensibus, sale dicat cu mea. Ex has nulla lucilius tractatos, ne dicat integre oporteat est.</p>


<p>Lorem ipsum dolor sit amet, cum autem exerci te. Appareat legendos assentior ea nec. Et autem error eam. Detraxit posidonium voluptatibus ex sed, insolens instructior eu vel, per ex docendi perfecto. Utroque persecuti an est.</p>

<p>Ut est accumsan consequuntur, nec idque probatus postulant eu. Erant mollis complectitur ei eos, dicunt maluisset at sed, ut eum partem nonumes adipiscing. Ea debet ridens duo. Sit an errem essent, id alia viderer periculis vel. Vim sonet vocent intellegebat ne. Soluta commodo cu vel, case torquatos sed no. Ullum vocent interpretaris pro in, qui te clita accusam mentitum.</p>

<p>Vel no soleat rationibus. Ut stet euripidis vel, vidit nonumes gloriatur in vim. Quot labore eligendi ei his. Vel ne eleifend recteque omittantur. Et accusamus assentior mediocritatem sit, odio elaboraret dissentiunt ut pri. Duo semper doctus te, ne possit disputando cum.</p>

<p>Ad lorem putant vivendum sed, laudem verear no mel. Quaeque constituam interpretaris ea vix, munere argumentum per ea, et odio everti iriure pri. Eam ea vidisse omnesque tractatos. Iusto temporibus quo in, has id detracto consequat. At est intellegat necessitatibus.</p>

<p>Justo epicuri delicata an has, an nec augue labore comprehensam, an sit alii hendrerit. Purto brute voluptua vis ut. Pri erat labore at, admodum incorrupte quo et, ne dolorum admodum mei. Eu est viris assentior forensibus, sale dicat cu mea. Ex has nulla lucilius tractatos, ne dicat integre oporteat est.</p>


<p>Lorem ipsum dolor sit amet, cum autem exerci te. Appareat legendos assentior ea nec. Et autem error eam. Detraxit posidonium voluptatibus ex sed, insolens instructior eu vel, per ex docendi perfecto. Utroque persecuti an est.</p>

<p>Ut est accumsan consequuntur, nec idque probatus postulant eu. Erant mollis complectitur ei eos, dicunt maluisset at sed, ut eum partem nonumes adipiscing. Ea debet ridens duo. Sit an errem essent, id alia viderer periculis vel. Vim sonet vocent intellegebat ne. Soluta commodo cu vel, case torquatos sed no. Ullum vocent interpretaris pro in, qui te clita accusam mentitum.</p>

<p>Vel no soleat rationibus. Ut stet euripidis vel, vidit nonumes gloriatur in vim. Quot labore eligendi ei his. Vel ne eleifend recteque omittantur. Et accusamus assentior mediocritatem sit, odio elaboraret dissentiunt ut pri. Duo semper doctus te, ne possit disputando cum.</p>

<p>Ad lorem putant vivendum sed, laudem verear no mel. Quaeque constituam interpretaris ea vix, munere argumentum per ea, et odio everti iriure pri. Eam ea vidisse omnesque tractatos. Iusto temporibus quo in, has id detracto consequat. At est intellegat necessitatibus.</p>

<p>Justo epicuri delicata an has, an nec augue labore comprehensam, an sit alii hendrerit. Purto brute voluptua vis ut. Pri erat labore at, admodum incorrupte quo et, ne dolorum admodum mei. Eu est viris assentior forensibus, sale dicat cu mea. Ex has nulla lucilius tractatos, ne dicat integre oporteat est.</p>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img alt="Sigma" src="http://placehold.it/20x20">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-navbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home<span class="sr-only">(current)</span></a></li>
        <li><a href="/admin">Admin</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/showcase.html
{% extends "base.html" %}

{% block title %} Projetos - Sigma {% endblock %}

{% block body %}

<h1>Projetos do LEDS</h1>

<br>

<div class="row">
  {% for projeto in projetos %}
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="http://placehold.it/200x200" alt="Logo">
      <div class="caption">
        <h3> {{ projeto.nome | upper }} </h3>
        <p> {{ projeto.descricao | truncatewords:"50" }} </p>
        <p><a href="projetos/{{ projeto.id }}" class="btn btn-primary" role="button">Visualizar</a></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}